name: issue-comment-CI-test 

on:
  issue_comment:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: checkout PR 
      run: echo ${{ github.event.html_url }}
    - name: print body
      run: echo ${{ github.event.comment.body }}
