name: issue-comment-CI-test 

on:
  issue_comment:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
       ref: add-GOOGLE_APPLICATION_CREDENTIALS
    - name: print body
      run: echo ${{ github.event.comment.body }}
